import { promises as fs } from "node:fs";
import path from "node:path";
import { intro, select, text, isCancel, outro } from "@clack/prompts";
import {
  TEMPLATES,
  findTemplate,
  toPackageName,
} from "../lib/templates.js";
import {
  interactive,
  setJsonMode,
  isJsonMode,
  emitJson,
  say,
  done,
  fail,
} from "../lib/ui.js";
import type { InitOptions } from "../types.js";

async function pathExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

/**
 * repo-ai init — 脚手架新项目（默认 ts-cli 模板）。
 * 纯本地生成，不调用 LLM。
 */
export async function runInit(options: InitOptions): Promise<void> {
  setJsonMode(options.json === true);
  if (interactive && !isJsonMode()) intro("repo-ai init");

  // 1. 交互式选择模板（TTY 且未显式指定 --template）
  let templateId = options.template?.trim().toLowerCase();
  if (!templateId && interactive && !isJsonMode()) {
    const chosen = await select({
      message: "选择项目模板",
      options: TEMPLATES.map((t) => ({
        value: t.id,
        label: `${t.label} — ${t.description}`,
      })),
    });
    if (isCancel(chosen)) {
      outro("已取消");
      return;
    }
    templateId = chosen as string;
  }
  if (!templateId) templateId = "ts-cli";

  const template = findTemplate(templateId);
  if (!template) {
    fail(
      `未知模板: ${templateId}。可用: ${TEMPLATES.map((t) => t.id).join(", ")}`,
    );
    return;
  }

  // 2. 确定目标目录与名称（TTY 且未给 name 时提示输入）
  const cwd = process.cwd();
  let rawName = (options.name ?? "").trim();
  if (!rawName && interactive && !isJsonMode()) {
    const input = await text({
      message: "项目名（回车使用当前目录名）",
      placeholder: path.basename(cwd),
    });
    if (isCancel(input)) {
      outro("已取消");
      return;
    }
    rawName = (input ?? "").trim();
  }
  const isExplicitDir = rawName !== "" && rawName !== ".";
  const targetDir = isExplicitDir ? path.resolve(cwd, rawName) : cwd;
  const name = isExplicitDir ? rawName : path.basename(cwd);
  const vars = {
    name,
    packageName: toPackageName(name),
    description: `${name} — generated by repo-ai-cli`,
  };

  // 3. 生成文件
  const created: string[] = [];
  const skipped: string[] = [];
  for (const [rel, contentFn] of Object.entries(template.files)) {
    const abs = path.join(targetDir, rel);
    if (!options.force && (await pathExists(abs))) {
      skipped.push(rel);
      continue;
    }
    await fs.mkdir(path.dirname(abs), { recursive: true });
    await fs.writeFile(abs, contentFn(vars), "utf8");
    created.push(rel);
  }

  // 4. 输出结果
  if (isJsonMode()) {
    emitJson({
      ok: true,
      template: template.id,
      directory: targetDir,
      name: vars.name,
      packageName: vars.packageName,
      created,
      skipped,
    });
    return;
  }

  say(`模板: ${template.label} (${template.id})`);
  say(`目录: ${targetDir}`);
  for (const rel of created) say(`  + ${rel}`);
  for (const rel of skipped) say(`  · 已存在，跳过: ${rel}`);
  done("初始化完成");
  if (created.length > 0) {
    console.log("下一步:");
    console.log(isExplicitDir ? `  cd ${rawName}` : `  # 当前目录`);
    console.log("  npm install");
    console.log("  npm run build && npm test");
  }
}